import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Module 1: The Robotic Nervous System (ROS 2)',
      items: [
        {
          type: 'autogenerated',
          dirName: 'module-1',
        },
      ],
    },
    {
      type: 'category',
      label: 'Module 2: The Digital Twin (Gazebo & Unity)',
      items: [
        {
          type: 'autogenerated',
          dirName: 'module-2',
        },
      ],
    },
    {
      type: 'category',
      label: 'Module 3: The AI-Robot Brain (NVIDIA Isaac)',
      items: [
        {
          type: 'autogenerated',
          dirName: 'module-3',
        },
      ],
    },
    {
      type: 'category',
      label: 'Module 4: Vision-Language-Action (VLA)',
      items: [
        {
          type: 'autogenerated',
          dirName: 'module-4',
        },
      ],
    },
    {
      type: 'category',
      label: 'Hardware Guide',
      items: [
        {
          type: 'autogenerated',
          dirName: 'hardware',
        },
      ],
    },
    {
      type: 'category',
      label: 'Weekly Breakdown',
      items: [
        {
          type: 'autogenerated',
          dirName: 'weekly-breakdown',
        },
      ],
    },
  ],
};

export default sidebars;
