import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Introduction',
      collapsible: true,
      collapsed: false,
      items: [
        'intro',
        'why-physical-ai',
        'learning-outcomes',
      ],
    },
    {
      type: 'category',
      label: 'Module 1: The Robotic Nervous System (ROS 2)',
      collapsible: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'module-1',
        },
      ],
    },
    {
      type: 'category',
      label: 'Module 2: The Digital Twin (Gazebo & Unity)',
      collapsible: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'module-2',
        },
      ],
    },
    {
      type: 'category',
      label: 'Module 3: The AI-Robot Brain (NVIDIA Isaac)',
      collapsible: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'module-3',
        },
      ],
    },
    {
      type: 'category',
      label: 'Module 4: Vision-Language-Action (VLA)',
      collapsible: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'module-4',
        },
      ],
    },
    {
      type: 'category',
      label: 'Hardware Guide',
      collapsible: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'hardware',
        },
      ],
    },
    {
      type: 'category',
      label: 'Weekly Breakdown',
      collapsible: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'weekly-breakdown',
        },
      ],
    },
    {
      type: 'category',
      label: 'Assessments',
      collapsible: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'assessments',
        },
      ],
    },
  ],
};

export default sidebars;
